version: "3.8"

services:

  microros_agent:
    image: puzzlebot
    container_name: microros_agent
    network_mode: host
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: >
      ros2 run micro_ros_agent micro_ros_agent
      serial --dev /dev/ttyUSB0 -b 115200
    restart: unless-stopped

  odometry:
    image: puzzlebot
    container_name: odometry
    network_mode: host
    command: ros2 run straight_line odometry
    depends_on:
      - microros_agent
    restart: unless-stopped

  pd_controller:
    image: puzzlebot
    container_name: pd_controller
    network_mode: host
    command: ros2 run straight_line pd_controller
    depends_on:
      - odometry
    restart: unless-stopped